#NAME: Wing Han So, Chungchhay Kuoch
#EMAIL: stellawhso@engineering.ucla.edu, chungchhay@ucla.edu
#ID: 804757943, 004843308                                                                 

files=lab3b.py Makefile README

default:
	cp lab3b.py lab3b
	chmod u+x lab3b lab3b.py

clean:
	rm -rf *.o *.tar.gz lab3b

dist: 
	tar -zczf lab3b-004843308.tar.gz $(files)

check: dist
	./P3B_check.sh 804757943


















