#NAME: Chungchhay Kuoch
#EMAIL: chungchhaykuoch@yahoo.com
#ID: 004 843 308

default: 
	gcc -o lab4b lab4b.c -lm -lmraa -Wall -Wextra

check:
	./lab4b < test.txt

clean: 
	rm *.tar.gz

dist:
	tar -cvzf lab4b-004843308.tar.gz lab4b.c LOGFILE test.txt README Makefile
